ignoredBuiltDependencies:
    - "@parcel/watcher"
    - "@tailwindcss/oxide"
    - better-sqlite3
    - esbuild
    - sharp
    - sqlite3
    - unrs-resolver
    - vue-demi

onlyBuiltDependencies:
    - better-sqlite3
    - sharp
    - sqlite3
